# Generated by Django 4.2.5 on 2023-09-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("page_count", models.IntegerField()),
                ("publish_date", models.DateField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
